import React from 'react';
import { Typography, Row, Col } from 'antd';
import FeatureList from './FeatureList';
import UserStoryMap from './UserStoryMap';
import NFRWizard from './NFRWizard';

const { Title, Paragraph } = Typography;

const RequirementAnalysisPage: React.FC = () => {
  return (
    <div>
      <Title level={2}>Requirement Analysis</Title>
      <Paragraph>
        Review the features and user stories generated by the AI. You can edit, prioritize, and add non-functional requirements.
      </Paragraph>
      <Row gutter={16}>
        <Col span={12}>
          <FeatureList />
        </Col>
        <Col span={12}>
          <UserStoryMap />
        </Col>
      </Row>
      <Row style={{ marginTop: 16 }}>
        <Col span={24}>
          <NFRWizard />
        </Col>
      </Row>
    </div>
  );
};

export default RequirementAnalysisPage;
